/-
Copyright (c) 2024 Amazon.com, Inc. or its affiliates. All Rights Reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jean-Baptiste Tristan
-/
import SHerLOC.Constants
import SHerLOC.Identifiers

/-!
# Operations

-/

inductive Operation where
  | abs (operand  : ValueID) (result  : ValueID)
  | add (lhs rhs  : ValueID) (result  : ValueID)
  | after_all (inputs  : ValueID) (result  : ValueID)
  | all_gather (operands  : ValueID) (all_gather_dim replica_groups channel_id use_global_device_ids  : Constant) (results  : ValueID)
  | all_reduce (operands  : ValueID) (computation  : FuncID) (replica_groups channel_id use_global_device_ids  : Constant) (results  : ValueID)
  | all_to_all (operands  : ValueID) (split_dimension concat_dimension split_count replica_groups channel_id  : Constant) (results  : ValueID)
  | and (lhs rhs  : ValueID) (result  : ValueID)
  | atan2 (lhs rhs  : ValueID) (result  : ValueID)
  | batch_norm_grad (operand scale mean variance grad_output  : ValueID) (epsilon feature_index  : Constant) (grad_operand grad_scale grad_offset  : ValueID)
  | batch_norm_inference (operand scale offset mean variance  : ValueID) (epsilon feature_index  : Constant) (result  : ValueID)
  | batch_norm_training (operand scale offset  : ValueID) (epsilon feature_index  : Constant) (output batch_mean batch_var  : ValueID)
  | bitcast_convert (operand  : ValueID) (result  : ValueID)
  | broadcast_in_dim (operand  : ValueID) (broadcast_dimensions  : Constant) (result  : ValueID)
  | case (index branches  : ValueID) (results  : ValueID)
  | cbrt (operand  : ValueID) (result  : ValueID)
  | ceil (operand  : ValueID) (result  : ValueID)
  | cholesky (a  : ValueID) (lower  : Constant) (result  : ValueID)
  | clamp (min operand max  : ValueID) (result  : ValueID)
  | collective_broadcast (operand  : ValueID) (replica_groups channel_id  : Constant) (result  : ValueID)
  | collective_permute (operand  : ValueID) (source_target_pairs channel_id  : Constant) (result  : ValueID)
  | compare (lhs rhs comparison_direction compare_type  : ValueID) (result  : ValueID)
  | complex (lhs rhs  : ValueID) (result  : ValueID)
  | composite (inputs composite_attributes  : ValueID) (name decomposition version  : Constant) (results  : ValueID)
  | concatenate (inputs  : ValueID) (dimension  : Constant) (result  : ValueID)
  | constant (value  : Constant) (output  : ValueID)
  | convert (operand  : ValueID) (result  : ValueID)
  | convolution (lhs rhs precision_config  : ValueID) (window_strides padding lhs_dilation rhs_dilation window_reversal input_batch_dimension input_feature_dimension input_spatial_dimensions kernel_input_feature_dimension kernel_output_feature_dimension kernel_spatial_dimensions output_batch_dimension output_feature_dimension output_spatial_dimensions feature_group_count batch_group_count  : Constant) (result  : ValueID)
  | cosine (operand  : ValueID) (result  : ValueID)
  | count_leading_zeros (operand  : ValueID) (result  : ValueID)
  | custom_call (inputs  : ValueID) (call_target_name has_side_effect backend_config api_version called_computations  : Constant) (results  : ValueID)
  | divide (lhs rhs  : ValueID) (result  : ValueID)
  | dot_general (lhs rhs precision_config lhs_precision_type rhs_precision_type accumulation_type  : ValueID) (lhs_batching_dimensions rhs_batching_dimensions lhs_contracting_dimensions rhs_contracting_dimensions lhs_component_count rhs_component_count num_primitive_operations allow_imprecise_accumulation  : Constant) (result  : ValueID)
  | dynamic_broadcast_in_dim (operand output_dimensions  : ValueID) (broadcast_dimensions known_expanding_dimensions known_non_expanding_dimensions  : Constant) (result  : ValueID)
  | dynamic_conv (lhs rhs padding precision_config  : ValueID) (window_strides lhs_dilation rhs_dilation window_reversal input_batch_dimension input_feature_dimension input_spatial_dimensions kernel_input_feature_dimension kernel_output_feature_dimension kernel_spatial_dimensions output_batch_dimension output_feature_dimension output_spatial_dimensions feature_group_count batch_group_count  : Constant) (result  : ValueID)
  | dynamic_gather (operand start_indices slice_sizes  : ValueID) (offset_dims collapsed_slice_dims start_index_map index_vector_dim indices_are_sorted  : Constant) (result  : ValueID)
  | dynamic_iota (output_shape iota_dimension  : ValueID) (result  : ValueID)
  | dynamic_pad (operand padding_value edge_padding_low edge_padding_high interior_padding  : ValueID) (result  : ValueID)
  | dynamic_reshape (operand output_shape  : ValueID) (result  : ValueID)
  | dynamic_slice (operand start_indices  : ValueID) (slice_sizes  : Constant) (result  : ValueID)
  | dynamic_update_slice (operand update start_indices  : ValueID) (result  : ValueID)
  | exponential (operand  : ValueID) (result  : ValueID)
  | exponential_minus_one (operand  : ValueID) (result  : ValueID)
  | fft (operand fft_type  : ValueID) (fft_length  : Constant) (result  : ValueID)
  | floor (operand  : ValueID) (result  : ValueID)
  | gather (operand start_indices  : ValueID) (offset_dims collapsed_slice_dims operand_batching_dims start_indices_batching_dims start_index_map index_vector_dim slice_sizes indices_are_sorted  : Constant) (result  : ValueID)
  | get_dimension_size (operand  : ValueID) (dimension  : Constant) (result  : ValueID)
  | get_tuple_element (operand  : ValueID) (index  : Constant) (result  : ValueID)
  | if (pred  : ValueID) (true_branch false_branch  : FuncID) (results  : ValueID)
  | imag (operand  : ValueID) (result  : ValueID)
  | infeed (token  : ValueID) (infeed_config  : Constant) (results  : ValueID)
  | iota (iota_dimension  : ValueID) (output  : ValueID)
  | is_finite (x  : ValueID) (y  : ValueID)
  | log (operand  : ValueID) (result  : ValueID)
  | log_plus_one (operand  : ValueID) (result  : ValueID)
  | logistic (operand  : ValueID) (result  : ValueID)
  | map (inputs  : ValueID) (computation  : FuncID) (dimensions  : Constant) (result  : ValueID)
  | maximum (lhs rhs  : ValueID) (result  : ValueID)
  | minimum (lhs rhs  : ValueID) (result  : ValueID)
  | multiply (lhs rhs  : ValueID) (result  : ValueID)
  | negate (operand  : ValueID) (result  : ValueID)
  | not (operand  : ValueID) (result  : ValueID)
  | optimization_barrier (operand  : ValueID) (result  : ValueID)
  | or (lhs rhs  : ValueID) (result  : ValueID)
  | outfeed (inputs token  : ValueID) (outfeed_config  : Constant) (result  : ValueID)
  | pad (operand padding_value  : ValueID) (edge_padding_low edge_padding_high interior_padding  : Constant) (result  : ValueID)
  | partition_id (result  : ValueID)
  | popcnt (operand  : ValueID) (result  : ValueID)
  | power (lhs rhs  : ValueID) (result  : ValueID)
  | real (operand  : ValueID) (result  : ValueID)
  | recv (token channel_type  : ValueID) (channel_id is_host_transfer  : Constant) (results  : ValueID)
  | reduce (inputs init_values  : ValueID) (body  : FuncID) (dimensions  : Constant) (results  : ValueID)
  | reduce_precision (operand  : ValueID) (exponent_bits mantissa_bits  : Constant) (output  : ValueID)
  | reduce_scatter (operand  : ValueID) (computation  : FuncID) (scatter_dimension replica_groups channel_id use_global_device_ids  : Constant) (result  : ValueID)
  | reduce_window (inputs init_values  : ValueID) (body  : FuncID) (window_dimensions window_strides base_dilations window_dilations padding  : Constant) (results  : ValueID)
  | remainder (lhs rhs  : ValueID) (result  : ValueID)
  | replica_id (result  : ValueID)
  | reshape (operand  : ValueID) (result  : ValueID)
  | reverse (operand  : ValueID) (dimensions  : Constant) (result  : ValueID)
  | rng (a b rng_distribution  : ValueID) (shape  : Constant) (result  : ValueID)
  | rng_bit_generator (rng_algorithm initial_state  : ValueID) (output_state output  : ValueID)
  | round_nearest_afz (operand  : ValueID) (result  : ValueID)
  | round_nearest_even (operand  : ValueID) (result  : ValueID)
  | rsqrt (operand  : ValueID) (result  : ValueID)
  | scatter (inputs scatter_indices updates  : ValueID) (update_computation  : FuncID) (update_window_dims inserted_window_dims input_batching_dims scatter_indices_batching_dims scatter_dims_to_operand_dims index_vector_dim indices_are_sorted unique_indices  : Constant) (results  : ValueID)
  | select (pred on_true on_false  : ValueID) (result  : ValueID)
  | select_and_scatter (operand source init_value  : ValueID) (select scatter  : FuncID) (window_dimensions window_strides padding  : Constant) (result  : ValueID)
  | send (inputs token channel_type  : ValueID) (channel_id is_host_transfer  : Constant) (result  : ValueID)
  | shift_left (lhs rhs  : ValueID) (result  : ValueID)
  | shift_right_arithmetic (lhs rhs  : ValueID) (result  : ValueID)
  | shift_right_logical (lhs rhs  : ValueID) (result  : ValueID)
  | sign (operand  : ValueID) (result  : ValueID)
  | sine (operand  : ValueID) (result  : ValueID)
  | slice (operand  : ValueID) (start_indices limit_indices strides  : Constant) (result  : ValueID)
  | sort (inputs  : ValueID) (comparator  : FuncID) (dimension is_stable  : Constant) (results  : ValueID)
  | sqrt (operand  : ValueID) (result  : ValueID)
  | subtract (lhs rhs  : ValueID) (result  : ValueID)
  | tan (operand  : ValueID) (result  : ValueID)
  | tanh (operand  : ValueID) (result  : ValueID)
  | transpose (operand  : ValueID) (permutation  : Constant) (result  : ValueID)
  | triangular_solve (a b transpose_a  : ValueID) (left_side lower unit_diagonal  : Constant) (result  : ValueID)
  | tuple (val  : ValueID) (result  : ValueID)
  | uniform_dequantize (operand  : ValueID) (result  : ValueID)
  | uniform_quantize (operand  : ValueID) (result  : ValueID)
  | while (operand  : ValueID) (cond body  : FuncID) (results  : ValueID)
  | xor (lhs rhs  : ValueID) (result  : ValueID)
